networks:
  backend:
    external: true
    name: pi-infra_backend

services:
  exchange-connector:
    build:
      context: .
      dockerfile: services/exchange-connector/Dockerfile
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      - .env
    networks:
      - backend
    restart: unless-stopped