services:
  # grafana:
  #   build:
  #     context: .
  #     dockerfile: infra/grafana/Dockerfile
  #   volumes:
  #     - grafana_secrets:/run/secrets
  #   ports:
  #     - ${GRAFANA_PORT}:${GRAFANA_PORT}
  #   environment:
  #     - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
  #     - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
  #     - GF_SERVER_HTTP_PORT=${GRAFANA_PORT}
  #   healthcheck:
  #     test: ["CMD", "sh", "-c", "test -f /run/secrets/grafana_token && test -s /run/secrets/grafana_token"]
  #     # test -f /run/secrets/grafana_token - Check if the file exists
  #     # test -s /run/secrets/grafana_token - Check if the file is not empty
  #     interval: 10s
  #     timeout: 5s
  #     retries: 3
  #     start_period: 5s

  redis:
    build:
      context: .
      dockerfile: /infra/redis/Dockerfile
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  # exchange-connector:
  #   build:
  #     context: .
  #     dockerfile: services/exchange-connector/Dockerfile
  #   env_file:
  #     - .env
  #   depends_on:
  #     # grafana:
  #     #   condition: service_healthy
  #     redis:
  #       condition: service_healthy
  #   # volumes:
  #   #   - grafana_secrets:/run/secrets

# volumes:
#   grafana_secrets: